development:
  adapter: postgresql
  encoding: unicode
  database: bookmarks
  pool: 25
  username: vagrant
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: bookmarks_test
  pool: 25
  username: vagrant
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bookmarks-production
  host: localhost
  pool: 25
  username: vagrant
  password:

cucumber:
  <<: *test
